project:
  type: website

website:
  description: "Built with Quarto"
  site-url: https://kaitlynrm.github.io
  title: "Kaitlyn Rose Mitchell"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kaitlynrm
      - icon: linkedin
        href: https://www.linkedin.com/in/krmitch/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



