---
title: "About"
---

I study how ecological change ripples through human systems. My tools are **spatial modeling**, **uncertainty quantification**, and **field-informed data**; my goals are **healthier ecosystems** and **healthier people**.

**Strengths**
- Quantitative: Statistics (Species distribution models & Ecological niche modelling, geospatial statistics, remote sensing, Google Earth Engine, R)
- Domain: disease ecology, freshwater systems, invasive species, habitat modification & restoration
- Leadership: cross-sector collaboration, community engagement, scientific outreach, grant writing, academic mentoring

**Current themes**
- **Host-informed risk mapping:** How can we leverage symbiotic relationships to improve predicted (and projected) distributions?
- **Freshwater sustainability:** Does waste create novel habitat for organisms? What local stewardship actions protect against waste accumulation in the environment?
- **Invasions & connectivity:** Can we identify dispersal drivers of invasive species? How do we navigate invasive species management in limited resource settings?
- **Habitat Restoration:** Water infrastructure alters ecological communities and can negatively impact human health. Can restoration of key species improve health outcomes?

Let’s connect: krmitch<at>stanford.edu | mitchellrkaitlyn<at>gmail.com

